version: '3'

services:

    postgres:
        image: postgres:15.1
        container_name: familieheist_postgres
        ports:
            - 5432:5432
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
            timeout: 45s
            interval: 10s
            retries: 10
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=password
        volumes:
            - ./docker/db/scripts/:/docker-entrypoint-initdb.d/
            - ./docker/db/data:/var/lib/postgresql/data/

    keycloak:
        image: bitnami/keycloak:20.0.2
        container_name: familieheist_keycloak
        environment:
            KEYCLOAK_DATABASE_HOST: postgres
            KEYCLOAK_DATABASE_PORT: 5432
            KEYCLOAK_DATABASE_NAME: keycloak
            KEYCLOAK_DATABASE_USER: keycloak
            KEYCLOAK_DATABASE_SCHEMA: public
            KEYCLOAK_DATABASE_PASSWORD: keycloak
            KEYCLOAK_CREATE_ADMIN_USER: 'true'
            KEYCLOAK_ADMIN_USER: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
            KEYCLOAK_MANAGEMENT_USER: manager
            KEYCLOAK_MANAGEMENT_PASSWORD: manager
        ports:
            - 8180:8080
            - 8143:8443
            - 9990:9990
        depends_on:
            - postgres
