version: '3'

services:

    postgres:
        image: postgres
        ports:
            - 5432:5432
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
            timeout: 45s
            interval: 10s
            retries: 10
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=password
        volumes:
            - ./db/scripts/:/docker-entrypoint-initdb.d/
            - ./db/data:/var/lib/postgresql/data/

    keycloak:
        image: quay.io/keycloak/keycloak:latest
        environment:
            DB_VENDOR: POSTGRES
            DB_ADDR: postgres
            DB_DATABASE: keycloak
            DB_USER: keycloak
            DB_SCHEMA: public
            DB_PASSWORD: keycloak
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: admin
        ports:
            - 8180:8080
            - 9990:9990
        depends_on:
            - postgres
