app:
  name: Familie Heist
  description: Website for family coming from Heist-op-den-Berg and surroundings

server:
  port: 8000
  error:
    include-message: always

logging:
  level:
    root: ERROR
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    be.familieheist: DEBUG

spring:
  config:
    activate:
      on-profile: default
  webflux:
    base-path: /
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/familieheist
    username: localdev
    password: localdev
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-main.yml
    url: jdbc:postgresql://localhost:5432/familieheist
    username: localdev
    password: localdev
  jackson:
    time-zone: Europe/Brussels
    serialization:
      INDENT_OUTPUT: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/auth/realms/master

springdoc:
  swagger-ui:
    displayRequestDuration: true

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, env
  endpoint:
    health:
      show-details: always

info:
  app:
    environments: ${spring.config.activate.on-profile}
    name: ${app.name}
    description: { app.description }
    database:
      type: PostgreSQL
      url: ${spring.r2dbc.url}
    java:
      version: { java.version }
